from typing import Dict, List, Optional
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from core.models import CIEvent, ErrorContext, FixResult, FailureCategory


@dataclass
class ValidationResult:
    passed: bool
    output: str
    command: str


@dataclass
class FixPlan:
    files: List[str] = field(default_factory=list)
    changes: Dict[str, str] = field(default_factory=dict)
    validation_commands: List[str] = field(default_factory=list)
    root_cause: str = ""
    fix_description: str = ""


class BaseTechAdapter(ABC):
    @property
    @abstractmethod
    def tech(self) -> str:
        pass

    @abstractmethod
    def analyze_failure(self, logs: str, event: CIEvent) -> ErrorContext:
        pass

    @abstractmethod
    def plan_fix(self, error_ctx: ErrorContext, repo_files: Dict[str, str]) -> FixPlan:
        pass

    @abstractmethod
    def validate(self, workspace: str, plan: FixPlan) -> ValidationResult:
        pass

    @abstractmethod
    def get_default_validation_commands(self) -> List[str]:
        pass

    def build_pr_body(self, event: CIEvent, error_ctx: ErrorContext, plan: FixPlan) -> str:
        return (
            f"## Automated CI Remediation\n\n"
            f"**CI Failure**\n"
            f"- Repository: `{event.repo}`\n"
            f"- Branch: `{event.broken_branch}`\n"
            f"- Run ID: `{event.run_id}`\n"
            f"- Workflow: {event.workflow_name}\n"
            f"- Job: {event.job_name}\n"
            f"- Technology: `ci_{self.tech}`\n\n"
            f"**Root Cause**\n{plan.root_cause}\n\n"
            f"**Fix Applied**\n{plan.fix_description}\n\n"
            f"**Files Changed**\n"
            + "\n".join(f"- `{f}`" for f in plan.files)
            + f"\n\n**Validation Performed**\n{plan.validation_commands}\n\n"
            f"---\n*This PR was automatically generated by the CI Remediation Agent.*"
        )
